### ISSUE TITLE
Getting error starting loopback 2 on 1.1.0

### ISSUE THREAD

**Issue by peter-holcomb-sp** [fullcube/loopback-ds-readonly-mixin#14]
Getting the following with 1.1.0.  Solved this by reverting back to 1.0.1

```
C:\sites\rtview-cloud-api\node_modules\loopback-ds-readonly-mixin\lib\read-only.js:65
    Object.keys(Model.definition.settings.relations).forEach(relationName => {
           ^

TypeError: Cannot convert undefined or null to object
    at EventEmitter.<anonymous> (C:\sites\rtview-cloud-api\node_modules\loopback-ds-readonly-mixin\lib\read-only.js:65:12)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at EventEmitter.app.model (C:\sites\rtview-cloud-api\node_modules\loopback\lib\application.js:170:9)
    at C:\sites\rtview-cloud-api\node_modules\loopback-boot\lib\executor.js:202:9
    at Array.forEach (native)
    at setupModels (C:\sites\rtview-cloud-api\node_modules\loopback-boot\lib\executor.js:198:23)
    at execute (C:\sites\rtview-cloud-api\node_modules\loopback-boot\lib\executor.js:39:3)
    at bootLoopBackApp (C:\sites\rtview-cloud-api\node_modules\loopback-boot\index.js:154:3)
    at Object.<anonymous> (C:\sites\rtview-cloud-api\server\server.js:50:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\lang\\nodejs\\node.exe" "C:\\lang\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rtview-cloud-api@1.0.1 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rtview-cloud-api@1.0.1 start script 'node .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rtview-cloud-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rtview-cloud-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rtview-cloud-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\sites\rtview-cloud-api\npm-debug.log
```

**Comment by peter-holcomb-sp** [comment]
I think that the issue is that some of my model json files don't have relation properties.  Perhaps you shoul do do check to see if relations exists?
